---
- name: Fetch smart proxies from the satellite
  uri:
    url: "https://{{ satellite_hostname }}/api/v2/smart_proxies"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs | default(True) }}"
    force_basic_auth: True
  register: result

- name: Output of results
  debug:
    msg: " {{ result['json'] }} "

- name: set the remote_execution_pubkey
  set_fact:
    remote_execution_pubkey: "{{ result['json'] | json_query('results[*].remote_execution_pubkey') | join('') }}"
    authorized_keys_file: "{{ authorized_keys_file | default('~/.ssh/authorized_keys') }}"

- name: Check if remote_execution_pubkey is in authorized_keys
  command: "grep -v '{{ remote_execution_pubkey }}' '{{ authorized_keys_file }}'"
  register: check_authorized
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Add the remote_execution_key to authorized keys
  lineinfile:
    path: "{{ authorized_keys_file }}"
    line: "{{ remote_execution_pubkey }}"
  when: check_authorized.rc == 0


