---

- name: "Upload the manifest"
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin }}"
    password: "{{ satellite_admin_password }}"
    server_url: "https://{{ publicname }}"
    organization: "{{ org }}"
    manifest_path: "{{ manifest_file }}"
    state: present
    validate_certs: no
  tags:
    - configure_satellite
    - configure_satellite_manifest
