---
- name: Copy manifest
  copy:
    src: "{{ manifest_file }}"
    dest: /tmp

- name: "Upload the manifest"
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin }}"
    password: "{{ satellite_admin_password }}"
    server_url: "https://{{ publicname }}"
    organization: "{{ org }}"
    manifest_path: "/tmp/{{ manifest_file | basename }}"
    state: present
    validate_certs: no
  tags:
    - configure_satellite
    - configure_satellite_manifest
