- name: Step 003 Pre Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 003 Pre Software"

    - import_role:
        name: infra-local-create-ssh_key
      when: set_env_authorized_key | bool

- name: Configure all hosts with Repositories
  hosts:
    - all:!windows:!hosts
  become: true
  gather_facts: False
  tags:
    - step004
    - common_tasks
  roles:
    - role: "set-repositories"
      vars:
        rhel_repos: "{{ satellite_rhel_repos }}"
        repo_method: "{{ satellite_repo_method }}"
        use_own_repos: "{{ satellite_use_own_repos }}"
      when: 'satellite_repo_method is defined'
    - { role: "set_env_authorized_key", when: 'set_env_authorized_key' }

- name: Configure all hosts with Repositories
  hosts:
    - hosts
  become: true
  gather_facts: False
  tags:
    - step004
    - common_tasks
  roles:
    - role: "set-repositories"
      vars:
        rhel_repos: "{{ hosts_rhel_repos }}"
        repo_method: "satellite"
        satellite_org: Red_Hat_GPTE_Labs
        satellite_activationkey: rhel8-summit
        satellite_url: labsat.opentlc.com
        use_content_view: false
    - role: "set_env_authorized_key"
      when: 'set_env_authorized_key'


- name: Configuring Bastion Hosts
  hosts: bastions
  become: true
  roles:
    - { role: "common", when: 'install_common' }
    - {role: "bastion", when: 'install_bastion' }
    - { role: "bastion-opentlc-ipa", when: 'install_ipa_client' }

  tags:
    - step004
    - bastion_tasks

- name: Install pip apypie for foreman-ansible-modules
  hosts: satellite
  become: true
  tasks:
    - pip:
        name: apypie

- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - presoftware_flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"
