---
- name: Unlock packages install
  command: foreman-maintain packages unlock

- name: Install libvirt
  package:
    name:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - libguestfs-tools
    - virt-install
    state: latest
  async: 3600
  poll: 36
  register: libvirt_install

- name: Unlock packages install
  command: foreman-maintain packages lock

- name: Start and enable libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Add foreman users to libvirt group
  user:
    name: "{{ item }}"
    groups: libvirt
    append: yes
  with_items:
    - foreman
    - foreman-proxy

- name: Get facts of default network
  virt_net:
    command: facts

- virt_net:
    command: destroy
    name: default

- name: Add tftp to default network
  virt_net:
    command: define
    name: default
    xml: '{{ lookup("template", "network/default.xml.j2") }}'

- virt_net:
    command: create
    name: default

# Define a new storage pool
- name: Get facts of pools
  virt_pool:
    command: facts

- debug:
    var: ansible_libvirt_pools
    verbosity: 2
- virt_pool:
    command: define
    name: vdisk
    xml: '{{ lookup("template", "pool/vdisk.xml.j2") }}'
  when: '"vdisk" not in ansible_libvirt_pools'
- virt_pool:
    command: create
    name: vdisk
  when: '"vdisk" not in ansible_libvirt_pools'

# - name: refresh capsule features
