:role: satellite-manage-manifest
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_manifest
:main_file: tasks/main.yml
:version_file: tasks/version_6.x.yml

Role: {role}
============

This role upload manifest onto satellite server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.


Role Variables
--------------

* Following are the variable which needs to be defined

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Optional | Organization label in string without space
|org_description: "String" |Optional | Organization description
|manifest_file: "String" |Required |Holds local or url path of manifest file
|cdn_repository_url: "String"|Optional | If to sync content from another cdn than https://cdn.redhat.com/
|===

* Exammple variables

[source=text]
----
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
manifest_file: /home/user/manifest.zip
cdn_repository_url: "http://my.local.com/cdn"
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_manifest

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_manifest
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
manifest_file: /home/user/manifest.zip
cdn_repository_url: "http://my.local.com/cdn"


[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-manifest

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, if necessary create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.x.yml]


Author Information
------------------

{author}
