---

# - name: Print inputs to script
#   debug:
#     msg: "{% if item.1.releasever is defined %}{{ item.1.releasever }}{% endif %}"
#   loop: "{{ satellite_content | subelements('repos') }}"

- name: Setting up satellite repository
  theforeman.foreman.katello_repository_set:
    username: "{{ satellite_admin }}"
    password: "{{ satellite_admin_password }}"
    server_url: "https://{{ publicname }}"
    validate_certs: no
    organization: "{{ org }}"
    name: "{{ item.1.name }}"
    product: "{{ item.1.product }}"
    repositories:
    - releasever: "{{ item.1.releasever | default(omit) }}"
      basearch: "{{ item.1.basearch | default(omit) }}"
  loop: "{{ satellite_content | subelements('repos') }}"
  tags:
    - configure_satellite
    - configure_satellite_subscription
