---

## Sync repositories
- name: Sync repository
  theforeman.foreman.katello_sync:
    username: "{{ satellite_admin }}"
    password: "{{ satellite_admin_password }}"
    server_url: "https://{{ publicname }}"
    validate_certs: no
    organization: "{{ org }}"
    product: "{{ item.1.product }}"
    repository: "{{ item.1.name | regex_replace('[()]')  + (' ' + item.1.basearch if item.1.basearch|d(None) else '' ) + ( ' ' + item.1.releasever if item.1.releasever|d(None)  else '' ) }}"
  loop: "{{ satellite_content | subelements('repos') }}"
  async: 999999
  poll: 0
  register: repo_sync_sleeper
  tags:
    - configure_satellite
    - configure_satellite_sync

- name: Wait until all Syncs have finished
  async_status:
    jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
  loop: "{{ repo_sync_sleeper.results }}"
  loop_control:
    loop_var: repo_sync_sleeper_item
  when: repo_sync_sleeper_item.ansible_job_id is defined  # Skip items that were skipped in the previous task
  register: async_job_result
  until: async_job_result.finished
  retries: 999
  delay: 20
  tags:
    - configure_satellite
    - configure_satellite_sync
