# vim: set ft=ansible:
---
- name: remove epel-release
  package:
    name: epel-release
    use: yum
    state: absent

- name: remove current repository files
  file:
    path: /etc/yum.repos.d/epel.repo
    state: absent
  tags:
    - configure_repos
    - remove_existing_repos

- name: remove current repository files
  file:
    path: /etc/yum.repos.d/epel-testing.repo
    state: absent
  tags:
    - configure_repos
    - remove_existing_repos
